//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicaEntities : DbContext
    {
        public ClinicaEntities()
            : base("name=ClinicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<documento> documento { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<log> log { get; set; }
        public virtual DbSet<notaevolucion> notaevolucion { get; set; }
        public virtual DbSet<paciente> paciente { get; set; }
        public virtual DbSet<pago> pago { get; set; }
        public virtual DbSet<tipo_documento> tipo_documento { get; set; }
        public virtual DbSet<tratamiento> tratamiento { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
