//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public string Uid { get; set; }
        public System.DateTime Fecha { get; set; }
        public byte Accion { get; set; }
        public string Valor { get; set; }
        public string Modulo { get; set; }
        public string Usuario { get; set; }
        public string IP { get; set; }
    }
}
