//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class notaevolucion
    {
        public long Id { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public long Paciente { get; set; }
        public string Usuario { get; set; }
        public int Estado { get; set; }
    
        public virtual estado estado1 { get; set; }
        public virtual paciente paciente1 { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
