//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago
    {
        public long Uid { get; set; }
        public long Tratamiento { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Folio { get; set; }
        public decimal Importe { get; set; }
        public string Concepto { get; set; }
    
        public virtual tratamiento tratamiento1 { get; set; }
    }
}
